import theme from '@/styles/theme'
import './globals.css'
import { ThemeProvider } from 'styled-components'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ThemeProvider theme={theme}>
            <html lang="en">
                <body>
                    <header></header>
                    <main>{children}</main>
                    <footer></footer>
                </body>
            </html>
        </ThemeProvider>
    )
}
